---
- name: Basic Linux tools installation
  hosts: localhost
  tasks: 
    - name: Install net-tools rpm-based
      block:
        - yum: name=net-tools state=present
      when: ansible_os_family == 'RedHat'
      become: yes
    - name: Install net-tools debian-based
      block:
        - apt: name=net-tools state=present
      when: ansible_os_family == 'Debian'
      become: yes

